services:
  - type: web
    name: Tamil-Blasters-RSS-Bot
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TOKEN
        value: "<your-bot-token>"
      - key: API_ID
        value: "<your-api-id>"
      - key: API_HASH
        value: "<your-api-hash>"
      - key: OWNER
        value: "<your-owner-id>"
      - key: CHANNEL_ID
        value: "<your-channel-id>"
      - key: PORT
        value: "8000"
